github.com:
    users:
        lawfullyillegal-droid:
            oauth_token: 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
    git_protocol: https
    user: lawfullyillegal-droid
    oauth_token: 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
